steps:
- task: UseDotNet@2
  displayName: 'Install .NET 6'
  inputs:
    version: 6.x

- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: restore
    verbosityRestore: normal
    projects: src/Pootis-Bot.sln

- task: DotNetCoreCLI@2
  displayName: Build Project
  inputs:
    command: build
    projects: src/Pootis-Bot.sln
    arguments: '--no-restore -v normal -c $(buildConfiguration)'

- task: PublishPipelineArtifact@1
  displayName: 'Upload Artifact'
  inputs:
    targetPath: src/bin/Release
    artifactName: $(Build.DefinitionName)-$(Agent.JobName)-$(Build.BuildNumber)-$(Build.SourceBranchName)
