<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Authors>Voltstro</Authors>
        <Copyright>Copyright (c) Voltstro 2018-2024</Copyright>
        
        <OutputType>Exe</OutputType>
        <RootNamespace>Pootis_Bot</RootNamespace>
        <ApplicationIcon>icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Discord.Net" Version="3.18.0" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.9" />
        <PackageReference Include="Victoria" Version="7.0.5" />
        <PackageReference Include="Wiki.Net" Version="4.1.1" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Pootis-Bot.Shared\Pootis-Bot.Shared.csproj" />
    </ItemGroup>

</Project>