// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pootis_Bot.Shared;
using Pootis_Bot.Shared.Messages;

#nullable disable

namespace Pootis_Bot.Shared.Migrations
{
    [DbContext(typeof(PootisBotDbContext))]
    [Migration("20250212122759_AddRole")]
    partial class AddRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "message_type", new[] { "goodbye", "welcome" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pootis_Bot.Shared.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_id");

                    b.Property<DateTime?>("LastXpMessageTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_xp_message_time");

                    b.Property<string>("ProfileMessage")
                        .HasColumnType("text")
                        .HasColumnName("profile_message");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_profile");

                    b.HasIndex("DiscordId")
                        .IsUnique()
                        .HasDatabaseName("ix_profile_discord_id");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("Pootis_Bot.Shared.Models.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_id");

                    b.Property<bool>("GoodbyeMessageEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("goodbye_message_enabled");

                    b.Property<decimal?>("RuleReactionChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("rule_reaction_channel_id");

                    b.Property<string>("RuleReactionEmoji")
                        .HasColumnType("text")
                        .HasColumnName("rule_reaction_emoji");

                    b.Property<bool>("RuleReactionEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("rule_reaction_enabled");

                    b.Property<decimal?>("RuleReactionMessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("rule_reaction_message_id");

                    b.Property<decimal?>("RuleReactionRoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("rule_reaction_role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("WelcomeGoodbyeChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("welcome_goodbye_channel_id");

                    b.Property<bool>("WelcomeMessageEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("welcome_message_enabled");

                    b.HasKey("Id")
                        .HasName("pk_server");

                    b.HasIndex("DiscordId")
                        .IsUnique()
                        .HasDatabaseName("ix_server_discord_id");

                    b.ToTable("server", (string)null);
                });

            modelBuilder.Entity("Pootis_Bot.Shared.Models.ServerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<MessageType>("Type")
                        .HasColumnType("message_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_server_message");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_server_message_server_id");

                    b.ToTable("server_message", (string)null);
                });

            modelBuilder.Entity("Pootis_Bot.Shared.Models.ServerMessage", b =>
                {
                    b.HasOne("Pootis_Bot.Shared.Models.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_server_message_server_server_id");

                    b.Navigation("Server");
                });
#pragma warning restore 612, 618
        }
    }
}
